name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarQube Scan
        run: |
          ./gradle sonarqube \
          -Dsonar.projectKey=Firstmini \
          -Dsonar.host.url=http://192.168.80.156:9000 \
          -Dsonar.login=sqp_8ca6ccbfa2e019aa4c702a20c695a0954406e0ce

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'my-app'
          scan: './'
          format: 'HTML'
          out: 'dependency-report'

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: dependency-report

      - name: Build Docker Image
        run: docker build -t myrepo/myapp:git@github.com:vipul3618/myrepo.git

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myrepo/myapp:git@github.com:vipul3618/myrepo.git'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: DockerHub Login
        run: echo "Vipul@#18" | docker login -u "Vipul1820" --password-stdin

      - name: Push Docker Image
        run: docker push myrepo/myapp:git@github.com:vipul3618/myrepo.git

      - name: Render Helm Template
        run: |
          helm dependency update helm/
          helm template myapp helm/ --set image.tag=git@github.com:vipul3618/myrepo.git > k8s-manifests/myapp.yaml

      - name: Commit Manifests
        run: |
          git config --global user.email "ci@myorg.com"
          git config --global user.name "CI Bot"
          git add k8s-manifests/
          git commit -m "Deploy git@github.com:vipul3618/myrepo.git"
          git push

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,message
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
